name: ETSWatch

channels:
  - conda-forge

dependencies:
  # core
  - python=3.7
  - jupyterlab
  - pip
  
  # data
  - xarray
  - pandas
  - numpy
  
  # plotting
  - seaborn
  - matplotlib

  # data retrieval
  - beautifulsoup4
  - html5lib
  - lxml
  - xmltodict
  
  # packaging/devops
  - twine
  - python-dotenv

  # nbdev/docs
  - mkdocs
  - mkdocs-material
  - typer

  - pip:
      - -e .
      - mplfinance
      - nbdev
      - ipypb
      - feautils
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix