site_name: ETS-Watch
repo_url: https://github.com/OSUKED/ETS-Watch
edit_uri: edit/main/docs/
repo_name: ETS-Watch
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest
  palette:
    primary: black

extra:
  generator: false
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - footnotes
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  
nav:
  - Home: index.md
  - Development:
    - Market Prices: 01-mkt-prices.md
    - Installations: 02-eutl-installations.md
    - Accounts: 03-eutl-accounts.md
    - CLI: 04-cli.md