name: Update data and visualisations

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "30 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        dir
        python -m pip install --upgrade pip
        python -m pip install pandas requests feautils matplotlib mplfinance ipython python-dotenv regex
        python update_data.py
        dir
      env: 
        USER_KEY: ${{ secrets.QUANDL_API_KEY  }}
      
    - uses: stefanzweifel/git-auto-commit-action@v4 
